inherit: configs/default.yaml

smarts:
  scenario: "/home/giovanni/SMARTS/scenarios/sumo/loop"
  agent_id: "Agent-007"
  agent_type: "LanerWithSpeed"
  max_episode_steps: 300
  use_dummy: false
  headless: true

reward:
  mode: "sparse"
  success_reward: 20.0
  collision_penalty: -5.0
  off_route_penalty: -8.0
  step_penalty: -0.002
  custom_success_distance: 0.0
