inherit: ../default.yaml

smarts:
  scenario: "/workspace/SMARTS/scenarios/sumo/intersections/1_to_2lane_left_turn_t_agents_1"
  agent_id: "Agent-007"
  agent_type: "LanerWithSpeed"
  max_episode_steps: 300
  use_dummy: false
  headless: true

reward:
  mode: "sparse"
  success_reward: 1.0
  collision_penalty: -1.0
  off_route_penalty: -1.0
  step_penalty: 0.0
  custom_success_distance: 0.0